name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ci_test:
    uses: nesrinTufan/test-repo/.github/workflows/ci-test.yml@main
    secrets: 
      git-token: ${{ secrets.GITHUB_TOKEN }}
    #with:
      #working-directory: .
    # secrets:
      # EE_CHECKOUT_TOKEN: ${{ secrets.EE_CHECKOUT_TOKEN }}
